version: "3"
services:
  pg:
    image: postgres:11.4-alpine
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5400:5400
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parkup
    restart: on-failure
  
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/backend
    ports:
      - 8000:8000
    depends_on:
      - pg
    restart: always